### ISSUE TITLE
Adjusting arduino .ino file

### ISSUE THREAD

**Issue by seans883** [PotatoX/Band_Saw_Conversion#3]
Is the sfm_slope defined in the .ino file what needs to be changed if i were to use this on a different size band saw? If so how did you calculate that number?

**Comment by PotatoX** [comment]
Let me know if the additional instructions help resolve your issue. Once you confirm I will close out issue.

**Comment by PotatoX** [comment]
Additional instruction are posted in the software  section.

**Comment by PotatoX** [comment]
Close
